// Command sol-api-doc renders human-readable markdown documentation from
// JSON Schema files generated by sol-api-gen.
//
// For each docs/api/<command>.schema.json it writes a docs/api/<command>.md
// with a description, top-level field table, and nested object details.
//
// Usage:
//
//	go run ./cmd/sol-api-doc
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// schema is a minimal representation of JSON Schema 2020-12, covering
// only the subset that sol-api-gen produces.
type schema struct {
	ID                   string            `json:"$id"`
	Schema               string            `json:"$schema"`
	Type                 string            `json:"type"`
	Format               string            `json:"format,omitempty"`
	Properties           map[string]schema `json:"properties,omitempty"`
	Items                *schema           `json:"items,omitempty"`
	Required             []string          `json:"required,omitempty"`
	AdditionalProperties any               `json:"additionalProperties,omitempty"`
}

// field is a flattened representation for the markdown table.
type field struct {
	Name        string
	Type        string
	Required    bool
	Description string
}

func main() {
	dir := filepath.Join("docs", "api")

	entries, err := os.ReadDir(dir)
	if err != nil {
		log.Fatalf("read dir: %v", err)
	}

	var schemaFiles []string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".schema.json") {
			schemaFiles = append(schemaFiles, e.Name())
		}
	}
	sort.Strings(schemaFiles)

	for _, f := range schemaFiles {
		inPath := filepath.Join(dir, f)
		cmdName := strings.TrimSuffix(f, ".schema.json")
		outPath := filepath.Join(dir, cmdName+".md")

		if err := renderMarkdown(inPath, outPath, cmdName); err != nil {
			log.Fatalf("render %q: %v", cmdName, err)
		}
		fmt.Printf("wrote %s\n", outPath)
	}
}

func renderMarkdown(inPath, outPath, cmdName string) error {
	data, err := os.ReadFile(inPath)
	if err != nil {
		return err
	}

	var s schema
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("parse schema: %w", err)
	}

	var b strings.Builder

	// Header.
	fmt.Fprintf(&b, "# %s\n\n", cmdName)
	fmt.Fprintf(&b, "JSON Schema for the `%s` command.\n\n", cmdName)
	fmt.Fprintf(&b, "**Schema file**: [%s.schema.json](%s.schema.json)\n\n", cmdName, cmdName)

	// Top-level fields table.
	reqSet := toSet(s.Required)
	fields := extractFields(s, reqSet)

	if len(fields) > 0 {
		b.WriteString("## Fields\n\n")
		writeFieldTable(&b, fields)
	}

	// Nested objects — render a section for each top-level property that is
	// an object or array-of-objects.
	nestedNames := make([]string, 0, len(s.Properties))
	for name := range s.Properties {
		nestedNames = append(nestedNames, name)
	}
	sort.Strings(nestedNames)

	for _, name := range nestedNames {
		prop := s.Properties[name]
		nested := resolveObject(prop)
		if nested == nil || len(nested.Properties) == 0 {
			continue
		}
		nReqSet := toSet(nested.Required)
		nFields := extractFields(*nested, nReqSet)
		if len(nFields) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n### %s\n\n", name)
		writeFieldTable(&b, nFields)

		// One more level deep — sub-objects within the nested object.
		subNames := make([]string, 0, len(nested.Properties))
		for sn := range nested.Properties {
			subNames = append(subNames, sn)
		}
		sort.Strings(subNames)

		for _, sn := range subNames {
			sp := nested.Properties[sn]
			sub := resolveObject(sp)
			if sub == nil || len(sub.Properties) == 0 {
				continue
			}
			sReqSet := toSet(sub.Required)
			sFields := extractFields(*sub, sReqSet)
			if len(sFields) == 0 {
				continue
			}
			fmt.Fprintf(&b, "\n#### %s.%s\n\n", name, sn)
			writeFieldTable(&b, sFields)
		}
	}

	return os.WriteFile(outPath, []byte(b.String()), 0o644)
}

// resolveObject returns the schema for the "object" portion of prop.
// If prop is an object with properties, it returns &prop.
// If prop is an array whose items are an object, it returns items.
// Otherwise nil.
func resolveObject(prop schema) *schema {
	if prop.Type == "object" && len(prop.Properties) > 0 {
		return &prop
	}
	if prop.Type == "array" && prop.Items != nil && prop.Items.Type == "object" && len(prop.Items.Properties) > 0 {
		return prop.Items
	}
	return nil
}

func extractFields(s schema, reqSet map[string]bool) []field {
	names := make([]string, 0, len(s.Properties))
	for name := range s.Properties {
		names = append(names, name)
	}
	sort.Strings(names)

	fields := make([]field, 0, len(names))
	for _, name := range names {
		prop := s.Properties[name]
		fields = append(fields, field{
			Name:        name,
			Type:        describeType(prop),
			Required:    reqSet[name],
			Description: describeField(name, prop),
		})
	}
	return fields
}

func writeFieldTable(b *strings.Builder, fields []field) {
	b.WriteString("| Field | Type | Required | Description |\n")
	b.WriteString("|-------|------|----------|-------------|\n")
	for _, f := range fields {
		req := "no"
		if f.Required {
			req = "**yes**"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n",
			f.Name, f.Type, req, f.Description)
	}
}

// describeType returns a human-readable type string for a schema property.
func describeType(s schema) string {
	switch s.Type {
	case "array":
		if s.Items != nil {
			return describeType(*s.Items) + "[]"
		}
		return "array"
	case "object":
		if len(s.Properties) > 0 {
			return "object"
		}
		// additionalProperties map
		return "object"
	case "string":
		if s.Format != "" {
			return fmt.Sprintf("string (%s)", s.Format)
		}
		return "string"
	case "integer":
		return "integer"
	case "number":
		return "number"
	case "boolean":
		return "boolean"
	default:
		if s.Type != "" {
			return s.Type
		}
		return "any"
	}
}

// describeField generates a short description from the field name and type.
func describeField(name string, s schema) string {
	// Timestamp fields.
	if s.Format == "date-time" || strings.HasSuffix(name, "_at") {
		return "Timestamp (RFC 3339, UTC)"
	}
	// ID fields.
	if name == "id" {
		return "Unique identifier"
	}
	if ref, ok := strings.CutSuffix(name, "_id"); ok {
		ref = strings.ReplaceAll(ref, "_", " ")
		return fmt.Sprintf("Reference to %s", ref)
	}
	// Boolean fields.
	if s.Type == "boolean" {
		return boolDescription(name)
	}
	// Array or object — note the structure.
	if s.Type == "array" {
		return arrayDescription(name)
	}
	if s.Type == "object" && len(s.Properties) > 0 {
		return objectDescription(name)
	}

	return fieldNameToDescription(name)
}

func boolDescription(name string) string {
	parts := strings.Split(name, "_")
	return strings.Join(parts, " ")
}

func arrayDescription(name string) string {
	return fmt.Sprintf("List of %s", strings.ReplaceAll(name, "_", " "))
}

func objectDescription(name string) string {
	return fmt.Sprintf("%s details", strings.ReplaceAll(name, "_", " "))
}

func fieldNameToDescription(name string) string {
	return strings.ReplaceAll(name, "_", " ")
}

func toSet(items []string) map[string]bool {
	m := make(map[string]bool, len(items))
	for _, item := range items {
		m[item] = true
	}
	return m
}
